-- liquibase formatted sql

-- changeset demaz:1
create table if not exists notification_task
(
    id      bigint generated by default as identity primary key,
    chatId  bigint    not null,
    message text      not null,
    date    timestamp not null
)